### ISSUE TITLE
Exception Creating Label with x64 platform target

### ISSUE THREAD

**Issue by Curdie** [dymosoftware/DCD-SDK-Sample#1]
If you clone this solution, restore packages, change the platform target to x64 and attempt to open any dymo label file you will get an unhandled exception.

Unhandled Exception: DYMO.CrossPlatform.Common.DYMOSerializationException: Invalid label file: The 'DieCutLabel' element is not declared.
   at DYMO.LabelAPI.LabelHelper.Settings_ValidationEventHandler(Object sender, ValidationEventArgs e)
   at System.Xml.Schema.XmlSchemaValidator.SendValidationEvent(String code, String arg)
   at System.Xml.Schema.XmlSchemaValidator.ValidateElement(String localName, String namespaceUri, XmlSchemaInfo schemaInfo, String xsiType, String xsiNil, String xsiSchemaLocation, String xsiNoNamespaceSchemaLocation)
   at System.Xml.XsdValidatingReader.ProcessElementEvent()
   at System.Xml.XsdValidatingReader.Read()
   at System.Xml.XmlReader.MoveToContent()
   at DYMO.LabelAPI.DYMOLabel`1.Deserialize(XmlReader reader)
   at DYMO.CrossPlatform.Common.Helpers.SerializationHelper.Deserialize[T](XmlReader reader)
   at DYMO.LabelAPI.LabelHelper.ReadAndOpenLabel(XmlReader reader)
   at DYMO.LabelAPI.LabelHelper.OpenLabel(String filename)
   at DymoSDK.Implementations.DymoLabel.LoadLabelFromFilePath(String filePath)
   at WPFSDKSample.ViewModels.MainViewModel.OpenFileAction()

I need to print Dymo labels from a 64-bit Windows app. Is there a way for me to do that with DYMO Connect SDK?

**Comment by dymosoftware** [comment]
Hi @Curdie, DYMO.Connect.SDK v1.2.977.101 contains a fix that could help you with this issue. This version will accept most of labels created from DLS(.label). If this version does not fix the issue at all, try to open the label from DYMO Connect Software(DCD), if you are able to open from DCD then save it to get your label upgraded as DYMO Connect label(.dymo). I strongly recommend you to use DCD to create your further labels since SDK was built based on this.

**Comment by Curdie** [comment]
I am using 1.2.977.101. This isn't an issue with the label file; it happens with every label file including brand new sample files saved from DCD. In addition to the DYMOSerializationException, I sometimes receive the following exception:

Exception thrown: 'System.BadImageFormatException' in DYMO.LabelAPI.dll
An unhandled exception of type 'System.BadImageFormatException' occurred in DYMO.LabelAPI.dll
An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)

**Comment by Curdie** [comment]
This was just an issue of me not understanding build configurations. Not a problem with DCD SDK. Thanks for your help!
