### ISSUE TITLE
.dll file path doesn't make sense

### ISSUE THREAD

**Issue by Yarles404** [dymosoftware/DCD-SDK-Sample#43]
var dymoPrinter = DymoPrinter.Instance;
var printer = dymoPrinter.GetPrinters().FirstOrDefault() // Exception:

System.Exception: Error getting printers ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'file:///C:\Users\ehs_yarles\AppData\Local\Temp\Temporary ASP.NET Files\root\70c4f1f6\46e16c38\assembly\dl3\d91fbbb6\001e480d_a1d5d701\x86\PrintingSupportLibrary.dll' or one of its dependencies. The system cannot find the file specified.
   at DYMO.CrossPlatform.Common.Windows.Helpers.FileLoader.LoadAssembly(String assemblyName)
   at DYMO.LabelAPI.Windows.Printers.SpoolerMonitorGateway..ctor()
   at DYMO.LabelAPI.Windows.PrinterDiscovery.WindowsDeviceDiscoveryAgent..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at DYMO.CrossPlatform.Common.ServiceLocator.AssemblyCache.ExportedClass.CreateType[T]()
   at DYMO.CrossPlatform.Common.ServiceLocator.AssemblyCache.<>c__DisplayClass18_0`1.<CreateMany>b__0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at DYMO.LabelAPI.PrinterFactory.RefreshPrinters()
   at DymoSDK.Implementations.DymoPrinter.RefreshPrinters()
   at DymoSDK.Implementations.DymoPrinter.GetPrinters()
   --- End of inner exception stack trace ---
   at DymoSDK.Implementations.DymoPrinter.GetPrinters()
   at certs.Controllers.PackageController.PrintLabels(List`1 labels, String printerName) in C:\Users\ehs_yarles\Desktop\workspace\certs\certs\Controllers\PackageController.cs:line 110

Why is it looking for the assembly in C:\Users\ehs_yarles\AppData\Local\Temp\Temporary ASP.NET Files\root\70c4f1f6\46e16c38\assembly\dl3\d91fbbb6\001e480d_a1d5d701\x86\PrintingSupportLibrary.dll ???

Assembly is here:
C:\Users\ehs_yarles\.nuget\packages\dymo.connect.sdk\1.4.2.35\Build\DYMOLib\x86\PrintingSupportLibrary.dll, as expected

**Comment by edsonh** [comment]
So I assume this was never fixed because I'm having the same issue. Any suggestions?

**Comment by Yarles404** [comment]
No, they either don't have developers who can help or don't care.

**Comment by edsonh** [comment]
Well that sucks. I can get this to work on with a 450 turbo but not the 550. Do you have .net Framework 3.5 installed? Have you tried to see if its because of that. I see some forum responses are saying that the SDK is dependent on the .Net 3.5 Framework

**Comment by edsonh** [comment]
#22  This might help

**Comment by edsonh** [comment]
#16

**Comment by hx-paco** [comment]
Still, same issue and others related to this one are alive after 3 years open (#11,  #16 ). 
If Dymo don't want to spend time/resources on solving real, critical and urgent problems for their clients, why not trying to opensource your SDK? or is it better that we say to our customers to go for Brother printers instead?
