### ISSUE TITLE
javascript sample code doesn't work on 550 printer

### ISSUE THREAD

**Issue by darojuv-aegis** [dymosoftware/DCD-SDK-Sample#62]
I updated PreviewAndPrintLabel.js under the PreviewAndPrintLabel javascript sample and attached it to this issue then tried both 'PreviewLabelFramework.dymo' and 'PreviewLabelFramework.label' files, but throw an error.

[PreviewAndPrintLabel.zip](https://github.com/dymosoftware/DCD-SDK-Sample/files/9177103/PreviewAndPrintLabel.zip)

ERROR:
dymo.connect.framework.js:2 Uncaught Error: ReadElementContentAs() methods cannot be called on an element that has child elements. Line 3, position 6.

ReadElementContentAs() methods cannot be called on an element that has child elements. Line 3, position 6.: Bad Request
    at ajaxSync (dymo.connect.framework.js:2:258525)
    at invokeWsCommand (dymo.connect.framework.js:2:260979)
    at DlsWebService.renderLabel (dymo.connect.framework.js:2:261614)
    at Object.renderLabel (dymo.connect.framework.js:2:319522)
    at dymo.label.framework.renderLabel (dymo.connect.framework.js:2:340701)
    at dymo.label.framework.Label.render (dymo.connect.framework.js:2:272924)
    at updatePreview (PreviewAndPrintLabel.js:46:33)
    at labelFile.onchange (PreviewAndPrintLabel.js:182:13)

**Comment by jpivac** [comment]
Did you ever find a solution to this? We're getting it when printing on a Mac, using a specific label size S0722550.
Using standard Address Labels S0722370 on the Mac it prints fine.
