### ISSUE TITLE
Web service cannot use label files from desktop application

### ISSUE THREAD

**Issue by SimFre** [dymosoftware/DCD-SDK-Sample#71]
Trying to use the JavaScript SDK. But running into issues. Seems the web service cannot handle label files that were designed in the bundled application.

`Uncaught (in promise) Error: ReadElementContentAs() methods cannot be called on an element that has child elements. Line 3, position 6.

ReadElementContentAs() methods cannot be called on an element that has child elements. Line 3, position 6.: Bad Request
    at ajaxSync (dymo.connect.framework.full.js:32924:12)
    at invokeWsCommand (dymo.connect.framework.full.js:33138:12)
    at DlsWebService.renderLabel (dymo.connect.framework.full.js:33168:11)
    at _framework.renderLabel (dymo.connect.framework.full.js:39176:100)
    at dymo.label.framework.renderLabel (dymo.connect.framework.full.js:40988:31)
    at dymo.label.framework.Label.render (dymo.connect.framework.full.js:34527:33)
    at Proxy.xdymo (JiraSearch.vue:103:25)`

Also, it would be very helpful to be able to set hostname and port for web service in the framework so it can be hosted elsewhere. This should also help out with the CORS issues.

Ideally, Dymo should try to collect all resources that are currently on old and new platforms, because right now there's a bit here, a bit there, a blog here, a github there. So many loose ends.

**Comment by SimFre** [comment]
Looks like the application is saving files with UTF-8 BOM, but the service is not accepting that.
