### ISSUE TITLE
Error on C# VS 2022 Project using DymoSDK: Could not load file or assembly

### ISSUE THREAD

**Issue by robertterrygoftx** [dymosoftware/DCD-SDK-Sample#86]
I am working in VS 2022 and have been implementing DYMO.Connect.SDK 1.4.4.21 
Works fine when i'm running in debug or release mode, but after I compile and build an .exe in a bundle, it fails on me. 

For some reason it's looking for assemblies in x86/x86 folder, a second one nested in teh first.  When that is corrected it builds correctly but fails and freezes my program. 

I have already verified i'm using the latest version of the SDK as well as made sure that the Skia is up to date with the version included in the Nuget.   I also attempted to update SKIA to latest version and it gave me the same error. 

Part of error here. 
Error ==== Message => Could not load file or assembly 'file:///C:\Program Files (x86)\...\...\DYMO.CrossPlatform.Common.PlatformSpecific.dll' or one of its dependencies. The system cannot find the file specified.
StackTrace =>    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at DYMO.CrossPlatform.Common.ServiceLocator.AssemblyCache..ctor()
   at DYMO.CrossPlatform.Common.ServiceLocator.ServiceLocator..ctor()
   at DYMO.CrossPlatform.Common.ServiceLocator.ServiceLocator.get_Instance()
   at DymoSDK.App.InitializePlatfSpec()
   at DymoSDK.App.Init()

**Comment by jotunskij** [comment]
I can't even run their own example program anymore. The Dymo SDK has cost my company sooo much time and support. I'm currently trying to persuade all of our clients to get a Zebra instead, because this SDK is a joke.

**Comment by digicommsol** [comment]
I have the same issue, if I run the application in x64 mode it works, but if I build it x86 mode, then the build process cannot find the following file in the following path:
.nuget\packages\dymo.connect.sdk\1.4.4.21\Build\DYMOLib\x86\x86\usps4cb.dll

It seems the reference has double x86/x86 by mistake. Can you please fix it Dymo?!!

**Comment by digicommsol** [comment]
I found a workaround for the current time to continue my build without errors and created the wrong path in my nuget cache folder and the build succeeded. I hope that Dymo will fix this path bug in the DYMO.Connect.SDK.targets file.

**Comment by robertterrygoftx** [comment]
> I found a workaround for the current time to continue my build without errors and created the wrong path in my nuget cache folder and the build succeeded. I hope that Dymo will fix this path bug in the DYMO.Connect.SDK.targets file.

I wouldn't hold my breath. Dymo development is dead from as far as I can see.
